-- insert de equipes do brasileirao 2020
INSERT INTO `equipe` (`equipe_id`, `nome_equipe`, `url_logo_equipe`) VALUES
(1, 'Atletico-GO', 'https://ssl.gstatic.com/onebox/media/sports/logos/9V6l9h3cJVQ0lqqX6-57zQ_96x96.png'),
(2, 'Atletico-MG', 'https://ssl.gstatic.com/onebox/media/sports/logos/q9fhEsgpuyRq58OgmSndcQ_96x96.png'),
(3, 'Athletico-PR', 'https://ssl.gstatic.com/onebox/media/sports/logos/LtpA9v-CQ_Qs2bgWVdDXxQ_96x96.png'),
(4, 'Bahia', 'https://ssl.gstatic.com/onebox/media/sports/logos/nIdbR6qIUDyZUBO9vojSPw_96x96.png'),
(5, 'Botafogo', 'https://ssl.gstatic.com/onebox/media/sports/logos/KLDWYp-H8CAOT9H_JgizRg_96x96.png'),
(6, 'Ceara', 'https://ssl.gstatic.com/onebox/media/sports/logos/mSl0cz3i2t8uv4zcprobOg_96x96.png'),
(7, 'Corinthians', 'https://ssl.gstatic.com/onebox/media/sports/logos/tCMSqgXVHROpdCpQhzTo1g_96x96.png'),
(8, 'Coritiba', 'https://ssl.gstatic.com/onebox/media/sports/logos/LaFlBADLmsjHfGTehCYtuA_96x96.png'),
(9, 'Flamengo', 'https://ssl.gstatic.com/onebox/media/sports/logos/orE554NToSkH6nuwofe7Yg_96x96.png'),
(10, 'Fluminense', 'https://ssl.gstatic.com/onebox/media/sports/logos/fCMxMMDF2AZPU7LzYKSlig_96x96.png'),
(11, 'Fortaleza', 'https://ssl.gstatic.com/onebox/media/sports/logos/me10ephzRxdj45zVq1Risg_96x96.png'),
(12, 'Goias', 'https://ssl.gstatic.com/onebox/media/sports/logos/gb8bo2x00XsbvsVp9nGniA_96x96.png'),
(13, 'Gremio', 'https://ssl.gstatic.com/onebox/media/sports/logos/Ku-73v_TW9kpex-IEGb0ZA_96x96.png'),
(14, 'Internacional', 'https://ssl.gstatic.com/onebox/media/sports/logos/OWVFKuHrQuf4q2Wk0hEmSA_96x96.png'),
(15, 'Palmeiras', 'https://ssl.gstatic.com/onebox/media/sports/logos/7spurne-xDt2p6C0imYYNA_96x96.png'),
(16, 'RB Bragantino', 'https://ssl.gstatic.com/onebox/media/sports/logos/KR_KUEAw5NGP0npb2dOpig_96x96.png'),
(17, 'Santos', 'https://ssl.gstatic.com/onebox/media/sports/logos/VHdNOT6wWOw_vJ38GMjMzg_96x96.png'),
(18, 'Sao Paulo', 'https://ssl.gstatic.com/onebox/media/sports/logos/4w2Z97Hf9CSOqICK3a8AxQ_96x96.png'),
(19, 'Sport', 'https://ssl.gstatic.com/onebox/media/sports/logos/u9Ydy0qt6JJjWhTaI6r10A_96x96.png'),
(20, 'Vasco da Gama', 'https://ssl.gstatic.com/onebox/media/sports/logos/_4RUqwd5euAxf0MtbPwq4A_96x96.png');